
/* File generated by gen_cfile.py. Should not be modified. */

#include "TestMaster.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS32 ID1 = 0x0;		/* Mapped at index 0x2000, subindex 0x00 */
UNS32 ID2 = 0x0;		/* Mapped at index 0x2001, subindex 0x00 */
UNS32 ID3 = 0x0;		/* Mapped at index 0x2002, subindex 0x00 */
UNS32 ID4 = 0x0;		/* Mapped at index 0x2003, subindex 0x00 */
UNS32 ID5 = 0x0;		/* Mapped at index 0x2004, subindex 0x00 */
UNS32 ID6 = 0x0;		/* Mapped at index 0x2005, subindex 0x00 */
UNS32 ID7 = 0x0;		/* Mapped at index 0x2006, subindex 0x00 */
UNS32 ID8 = 0x0;		/* Mapped at index 0x2007, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 TestMaster_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 TestMaster_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 TestMaster_iam_a_slave = 0;

TIMER_HANDLE TestMaster_heartBeatTimers[8] = {TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE};

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 TestMaster_obj1000 = 0x12D;	/* 301 */
                    subindex TestMaster_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 TestMaster_obj1001 = 0x0;	/* 0 */
                    subindex TestMaster_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 TestMaster_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t TestMaster_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex TestMaster_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 TestMaster_obj1005 = 0x40000080;	/* 1073741952 */
                    ODCallback_t TestMaster_Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestMaster_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 TestMaster_obj1006 = 0x0;	/* 0 */
                    ODCallback_t TestMaster_Index1006_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestMaster_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1006 }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 TestMaster_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 TestMaster_obj100D = 0x0;   /* 0 */

/* index 0x1010 :   Store parameters. */
                    UNS8 TestMaster_highestSubIndex_obj1010 = 4; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1010_Save_All_Parameters = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1010_Save_Communication_Parameters = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1010_Save_Application_Parameters = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1010_Save_Manufacturer_Parameters_1 = 0x0;	/* 0 */
                    subindex TestMaster_Index1010[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1010 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1010_Save_All_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1010_Save_Communication_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1010_Save_Application_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1010_Save_Manufacturer_Parameters_1 }
                     };

/* index 0x1011 :   Restore Default Parameters. */
                    UNS8 TestMaster_highestSubIndex_obj1011 = 4; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1011_Restore_All_Default_Parameters = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1011_Restore_Communication_Default_Parameters = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1011_Restore_Application_Default_Parameters = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1011_Restore_Manufacturer_Defined_Default_Parameters_1 = 0x0;	/* 0 */
                    subindex TestMaster_Index1011[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1011 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1011_Restore_All_Default_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1011_Restore_Communication_Default_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1011_Restore_Application_Default_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1011_Restore_Manufacturer_Defined_Default_Parameters_1 }
                     };

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 TestMaster_obj1014 = 0x80;	/* 128 */
                    subindex TestMaster_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1014 }
                     };

/* index 0x1016 :   Consumer Heartbeat Time. */
                    UNS8 TestMaster_highestSubIndex_obj1016 = 8; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1016[] = 
                    {
                      0x1EA60,	/* 125536 */
                      0x2EA60,	/* 191072 */
                      0x3EA60,	/* 256608 */
                      0x4EA60,	/* 322144 */
                      0x5EA60,	/* 387680 */
                      0x6EA60,	/* 453216 */
                      0x7EA60,	/* 518752 */
                      0x8EA60	/* 584288 */
                    };
                    subindex TestMaster_Index1016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1016 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1016[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1016[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1016[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1016[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1016[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1016[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1016[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1016[7] }
                     };

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 TestMaster_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 TestMaster_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex TestMaster_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1018_Serial_Number }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x601;	/* 1537 */
                    UNS32 TestMaster_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x581;	/* 1409 */
                    UNS8 TestMaster_obj1280_Node_ID_of_the_SDO_Server = 0x1;	/* 1 */
                    subindex TestMaster_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1281 :   Client SDO 2 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1281 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1281_COB_ID_Client_to_Server_Transmit_SDO = 0x602;	/* 1538 */
                    UNS32 TestMaster_obj1281_COB_ID_Server_to_Client_Receive_SDO = 0x582;	/* 1410 */
                    UNS8 TestMaster_obj1281_Node_ID_of_the_SDO_Server = 0x2;	/* 2 */
                    subindex TestMaster_Index1281[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1281 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1281_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1281_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1281_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1282 :   Client SDO 3 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1282 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1282_COB_ID_Client_to_Server_Transmit_SDO = 0x603;	/* 1539 */
                    UNS32 TestMaster_obj1282_COB_ID_Server_to_Client_Receive_SDO = 0x583;	/* 1411 */
                    UNS8 TestMaster_obj1282_Node_ID_of_the_SDO_Server = 0x3;	/* 3 */
                    subindex TestMaster_Index1282[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1282 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1282_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1282_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1282_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1283 :   Client SDO 4 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1283 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1283_COB_ID_Client_to_Server_Transmit_SDO = 0x604;	/* 1540 */
                    UNS32 TestMaster_obj1283_COB_ID_Server_to_Client_Receive_SDO = 0x584;	/* 1412 */
                    UNS8 TestMaster_obj1283_Node_ID_of_the_SDO_Server = 0x4;	/* 4 */
                    subindex TestMaster_Index1283[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1283 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1283_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1283_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1283_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1284 :   Client SDO 5 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1284 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1284_COB_ID_Client_to_Server_Transmit_SDO = 0x605;	/* 1541 */
                    UNS32 TestMaster_obj1284_COB_ID_Server_to_Client_Receive_SDO = 0x585;	/* 1413 */
                    UNS8 TestMaster_obj1284_Node_ID_of_the_SDO_Server = 0x5;	/* 5 */
                    subindex TestMaster_Index1284[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1284 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1284_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1284_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1284_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1285 :   Client SDO 6 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1285 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1285_COB_ID_Client_to_Server_Transmit_SDO = 0x606;	/* 1542 */
                    UNS32 TestMaster_obj1285_COB_ID_Server_to_Client_Receive_SDO = 0x586;	/* 1414 */
                    UNS8 TestMaster_obj1285_Node_ID_of_the_SDO_Server = 0x6;	/* 6 */
                    subindex TestMaster_Index1285[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1285 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1285_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1285_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1285_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1286 :   Client SDO 7 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1286 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1286_COB_ID_Client_to_Server_Transmit_SDO = 0x607;	/* 1543 */
                    UNS32 TestMaster_obj1286_COB_ID_Server_to_Client_Receive_SDO = 0x587;	/* 1415 */
                    UNS8 TestMaster_obj1286_Node_ID_of_the_SDO_Server = 0x7;	/* 7 */
                    subindex TestMaster_Index1286[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1286 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1286_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1286_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1286_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1287 :   Client SDO 8 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1287 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1287_COB_ID_Client_to_Server_Transmit_SDO = 0x608;	/* 1544 */
                    UNS32 TestMaster_obj1287_COB_ID_Server_to_Client_Receive_SDO = 0x588;	/* 1416 */
                    UNS8 TestMaster_obj1287_Node_ID_of_the_SDO_Server = 0x8;	/* 8 */
                    subindex TestMaster_Index1287[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1287 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1287_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1287_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1287_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1400_COB_ID_used_by_PDO = 0x181;	/* 385 */
                    UNS8 TestMaster_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1400_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1400_SYNC_start_value }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1401_COB_ID_used_by_PDO = 0x182;	/* 386 */
                    UNS8 TestMaster_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1401_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1401_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1401_SYNC_start_value }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1402_COB_ID_used_by_PDO = 0x183;	/* 387 */
                    UNS8 TestMaster_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1402_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1402_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1402_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1402_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1402_SYNC_start_value }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1403_COB_ID_used_by_PDO = 0x184;	/* 388 */
                    UNS8 TestMaster_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1403 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1403_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1403_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1403_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1403_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1403_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1403_SYNC_start_value }
                     };

/* index 0x1404 :   Receive PDO 5 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1404 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1404_COB_ID_used_by_PDO = 0x185;	/* 389 */
                    UNS8 TestMaster_obj1404_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1404_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1404_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1404_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1404_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index1404[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1404 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1404_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1404_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1404_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1404_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1404_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1404_SYNC_start_value }
                     };

/* index 0x1405 :   Receive PDO 6 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1405 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1405_COB_ID_used_by_PDO = 0x186;	/* 390 */
                    UNS8 TestMaster_obj1405_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1405_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1405_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1405_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1405_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index1405[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1405 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1405_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1405_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1405_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1405_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1405_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1405_SYNC_start_value }
                     };

/* index 0x1406 :   Receive PDO 7 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1406 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1406_COB_ID_used_by_PDO = 0x187;	/* 391 */
                    UNS8 TestMaster_obj1406_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1406_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1406_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1406_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1406_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index1406[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1406 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1406_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1406_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1406_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1406_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1406_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1406_SYNC_start_value }
                     };

/* index 0x1407 :   Receive PDO 8 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1407 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1407_COB_ID_used_by_PDO = 0x188;	/* 392 */
                    UNS8 TestMaster_obj1407_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1407_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1407_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1407_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1407_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index1407[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1407 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1407_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1407_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1407_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1407_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1407_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1407_SYNC_start_value }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1600 = 1; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1600[] = 
                    {
                      0x20000020	/* 536870944 */
                    };
                    subindex TestMaster_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600[0] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1601 = 1; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1601[] = 
                    {
                      0x20010020	/* 536936480 */
                    };
                    subindex TestMaster_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1601[0] }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1602 = 1; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1602[] = 
                    {
                      0x20020020	/* 537002016 */
                    };
                    subindex TestMaster_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1602 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1602[0] }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1603 = 1; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1603[] = 
                    {
                      0x20030020	/* 537067552 */
                    };
                    subindex TestMaster_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1603 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1603[0] }
                     };

/* index 0x1604 :   Receive PDO 5 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1604 = 1; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1604[] = 
                    {
                      0x20040020	/* 537133088 */
                    };
                    subindex TestMaster_Index1604[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1604 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1604[0] }
                     };

/* index 0x1605 :   Receive PDO 6 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1605 = 1; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1605[] = 
                    {
                      0x20050020	/* 537198624 */
                    };
                    subindex TestMaster_Index1605[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1605 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1605[0] }
                     };

/* index 0x1606 :   Receive PDO 7 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1606 = 1; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1606[] = 
                    {
                      0x20060020	/* 537264160 */
                    };
                    subindex TestMaster_Index1606[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1606 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1606[0] }
                     };

/* index 0x1607 :   Receive PDO 8 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1607 = 1; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1607[] = 
                    {
                      0x20070020	/* 537329696 */
                    };
                    subindex TestMaster_Index1607[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1607 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1607[0] }
                     };

/* index 0x1F22 :   Concise DCF. */
                    UNS8 TestMaster_highestSubIndex_obj1F22 = 2; /* number of subindex - 1*/
                    UNS8* TestMaster_obj1F22[] = 
                    {
                      (UNS8*)"",
                      (UNS8*)"\x01\x00\x00\x00\x17\x10\x00\x02\x00\x00\x00\xe8\x03"
                    };
                    subindex TestMaster_Index1F22[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1F22 },
                       { RW, domain, 0, (void*)&TestMaster_obj1F22[0] },
                       { RW, domain, 13, (void*)&TestMaster_obj1F22[1] }
                     };

/* index 0x2000 :   Mapped variable ID1 */
                    ODCallback_t ID1_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestMaster_Index2000[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&ID1 }
                     };

/* index 0x2001 :   Mapped variable ID2 */
                    ODCallback_t ID2_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestMaster_Index2001[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&ID2 }
                     };

/* index 0x2002 :   Mapped variable ID3 */
                    ODCallback_t ID3_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestMaster_Index2002[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&ID3 }
                     };

/* index 0x2003 :   Mapped variable ID4 */
                    ODCallback_t ID4_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestMaster_Index2003[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&ID4 }
                     };

/* index 0x2004 :   Mapped variable ID5 */
                    ODCallback_t ID5_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestMaster_Index2004[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&ID5 }
                     };

/* index 0x2005 :   Mapped variable ID6 */
                    ODCallback_t ID6_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestMaster_Index2005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&ID6 }
                     };

/* index 0x2006 :   Mapped variable ID7 */
                    ODCallback_t ID7_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestMaster_Index2006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&ID7 }
                     };

/* index 0x2007 :   Mapped variable ID8 */
                    ODCallback_t ID8_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestMaster_Index2007[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&ID8 }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable TestMaster_objdict[] = 
{
  { (subindex*)TestMaster_Index1000,sizeof(TestMaster_Index1000)/sizeof(TestMaster_Index1000[0]), 0x1000},
  { (subindex*)TestMaster_Index1001,sizeof(TestMaster_Index1001)/sizeof(TestMaster_Index1001[0]), 0x1001},
  { (subindex*)TestMaster_Index1005,sizeof(TestMaster_Index1005)/sizeof(TestMaster_Index1005[0]), 0x1005},
  { (subindex*)TestMaster_Index1006,sizeof(TestMaster_Index1006)/sizeof(TestMaster_Index1006[0]), 0x1006},
  { (subindex*)TestMaster_Index1010,sizeof(TestMaster_Index1010)/sizeof(TestMaster_Index1010[0]), 0x1010},
  { (subindex*)TestMaster_Index1011,sizeof(TestMaster_Index1011)/sizeof(TestMaster_Index1011[0]), 0x1011},
  { (subindex*)TestMaster_Index1014,sizeof(TestMaster_Index1014)/sizeof(TestMaster_Index1014[0]), 0x1014},
  { (subindex*)TestMaster_Index1016,sizeof(TestMaster_Index1016)/sizeof(TestMaster_Index1016[0]), 0x1016},
  { (subindex*)TestMaster_Index1018,sizeof(TestMaster_Index1018)/sizeof(TestMaster_Index1018[0]), 0x1018},
  { (subindex*)TestMaster_Index1280,sizeof(TestMaster_Index1280)/sizeof(TestMaster_Index1280[0]), 0x1280},
  { (subindex*)TestMaster_Index1281,sizeof(TestMaster_Index1281)/sizeof(TestMaster_Index1281[0]), 0x1281},
  { (subindex*)TestMaster_Index1282,sizeof(TestMaster_Index1282)/sizeof(TestMaster_Index1282[0]), 0x1282},
  { (subindex*)TestMaster_Index1283,sizeof(TestMaster_Index1283)/sizeof(TestMaster_Index1283[0]), 0x1283},
  { (subindex*)TestMaster_Index1284,sizeof(TestMaster_Index1284)/sizeof(TestMaster_Index1284[0]), 0x1284},
  { (subindex*)TestMaster_Index1285,sizeof(TestMaster_Index1285)/sizeof(TestMaster_Index1285[0]), 0x1285},
  { (subindex*)TestMaster_Index1286,sizeof(TestMaster_Index1286)/sizeof(TestMaster_Index1286[0]), 0x1286},
  { (subindex*)TestMaster_Index1287,sizeof(TestMaster_Index1287)/sizeof(TestMaster_Index1287[0]), 0x1287},
  { (subindex*)TestMaster_Index1400,sizeof(TestMaster_Index1400)/sizeof(TestMaster_Index1400[0]), 0x1400},
  { (subindex*)TestMaster_Index1401,sizeof(TestMaster_Index1401)/sizeof(TestMaster_Index1401[0]), 0x1401},
  { (subindex*)TestMaster_Index1402,sizeof(TestMaster_Index1402)/sizeof(TestMaster_Index1402[0]), 0x1402},
  { (subindex*)TestMaster_Index1403,sizeof(TestMaster_Index1403)/sizeof(TestMaster_Index1403[0]), 0x1403},
  { (subindex*)TestMaster_Index1404,sizeof(TestMaster_Index1404)/sizeof(TestMaster_Index1404[0]), 0x1404},
  { (subindex*)TestMaster_Index1405,sizeof(TestMaster_Index1405)/sizeof(TestMaster_Index1405[0]), 0x1405},
  { (subindex*)TestMaster_Index1406,sizeof(TestMaster_Index1406)/sizeof(TestMaster_Index1406[0]), 0x1406},
  { (subindex*)TestMaster_Index1407,sizeof(TestMaster_Index1407)/sizeof(TestMaster_Index1407[0]), 0x1407},
  { (subindex*)TestMaster_Index1600,sizeof(TestMaster_Index1600)/sizeof(TestMaster_Index1600[0]), 0x1600},
  { (subindex*)TestMaster_Index1601,sizeof(TestMaster_Index1601)/sizeof(TestMaster_Index1601[0]), 0x1601},
  { (subindex*)TestMaster_Index1602,sizeof(TestMaster_Index1602)/sizeof(TestMaster_Index1602[0]), 0x1602},
  { (subindex*)TestMaster_Index1603,sizeof(TestMaster_Index1603)/sizeof(TestMaster_Index1603[0]), 0x1603},
  { (subindex*)TestMaster_Index1604,sizeof(TestMaster_Index1604)/sizeof(TestMaster_Index1604[0]), 0x1604},
  { (subindex*)TestMaster_Index1605,sizeof(TestMaster_Index1605)/sizeof(TestMaster_Index1605[0]), 0x1605},
  { (subindex*)TestMaster_Index1606,sizeof(TestMaster_Index1606)/sizeof(TestMaster_Index1606[0]), 0x1606},
  { (subindex*)TestMaster_Index1607,sizeof(TestMaster_Index1607)/sizeof(TestMaster_Index1607[0]), 0x1607},
  { (subindex*)TestMaster_Index1F22,sizeof(TestMaster_Index1F22)/sizeof(TestMaster_Index1F22[0]), 0x1F22},
  { (subindex*)TestMaster_Index2000,sizeof(TestMaster_Index2000)/sizeof(TestMaster_Index2000[0]), 0x2000},
  { (subindex*)TestMaster_Index2001,sizeof(TestMaster_Index2001)/sizeof(TestMaster_Index2001[0]), 0x2001},
  { (subindex*)TestMaster_Index2002,sizeof(TestMaster_Index2002)/sizeof(TestMaster_Index2002[0]), 0x2002},
  { (subindex*)TestMaster_Index2003,sizeof(TestMaster_Index2003)/sizeof(TestMaster_Index2003[0]), 0x2003},
  { (subindex*)TestMaster_Index2004,sizeof(TestMaster_Index2004)/sizeof(TestMaster_Index2004[0]), 0x2004},
  { (subindex*)TestMaster_Index2005,sizeof(TestMaster_Index2005)/sizeof(TestMaster_Index2005[0]), 0x2005},
  { (subindex*)TestMaster_Index2006,sizeof(TestMaster_Index2006)/sizeof(TestMaster_Index2006[0]), 0x2006},
  { (subindex*)TestMaster_Index2007,sizeof(TestMaster_Index2007)/sizeof(TestMaster_Index2007[0]), 0x2007},
};

const indextable * TestMaster_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;*callbacks = TestMaster_Index1005_callbacks; break;
		case 0x1006: i = 3;*callbacks = TestMaster_Index1006_callbacks; break;
		case 0x1010: i = 4;break;
		case 0x1011: i = 5;break;
		case 0x1014: i = 6;break;
		case 0x1016: i = 7;break;
		case 0x1018: i = 8;break;
		case 0x1280: i = 9;break;
		case 0x1281: i = 10;break;
		case 0x1282: i = 11;break;
		case 0x1283: i = 12;break;
		case 0x1284: i = 13;break;
		case 0x1285: i = 14;break;
		case 0x1286: i = 15;break;
		case 0x1287: i = 16;break;
		case 0x1400: i = 17;break;
		case 0x1401: i = 18;break;
		case 0x1402: i = 19;break;
		case 0x1403: i = 20;break;
		case 0x1404: i = 21;break;
		case 0x1405: i = 22;break;
		case 0x1406: i = 23;break;
		case 0x1407: i = 24;break;
		case 0x1600: i = 25;break;
		case 0x1601: i = 26;break;
		case 0x1602: i = 27;break;
		case 0x1603: i = 28;break;
		case 0x1604: i = 29;break;
		case 0x1605: i = 30;break;
		case 0x1606: i = 31;break;
		case 0x1607: i = 32;break;
		case 0x1F22: i = 33;break;
		case 0x2000: i = 34;*callbacks = ID1_callbacks; break;
		case 0x2001: i = 35;*callbacks = ID2_callbacks; break;
		case 0x2002: i = 36;*callbacks = ID3_callbacks; break;
		case 0x2003: i = 37;*callbacks = ID4_callbacks; break;
		case 0x2004: i = 38;*callbacks = ID5_callbacks; break;
		case 0x2005: i = 39;*callbacks = ID6_callbacks; break;
		case 0x2006: i = 40;*callbacks = ID7_callbacks; break;
		case 0x2007: i = 41;*callbacks = ID8_callbacks; break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &TestMaster_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status TestMaster_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index TestMaster_firstIndex = {
  0, /* SDO_SVR */
  9, /* SDO_CLT */
  17, /* PDO_RCV */
  25, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const quick_index TestMaster_lastIndex = {
  0, /* SDO_SVR */
  16, /* SDO_CLT */
  24, /* PDO_RCV */
  32, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const UNS16 TestMaster_ObjdictSize = sizeof(TestMaster_objdict)/sizeof(TestMaster_objdict[0]); 

CO_Data TestMaster_Data = CANOPEN_NODE_DATA_INITIALIZER(TestMaster);

