
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef TESTMASTER_H
#define TESTMASTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 TestMaster_valueRangeTest (UNS8 typeValue, void * value);
const indextable * TestMaster_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data TestMaster_Data;
extern UNS32 ID1;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS32 ID2;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS32 ID3;		/* Mapped at index 0x2002, subindex 0x00*/
extern UNS32 ID4;		/* Mapped at index 0x2003, subindex 0x00*/
extern UNS32 ID5;		/* Mapped at index 0x2004, subindex 0x00*/
extern UNS32 ID6;		/* Mapped at index 0x2005, subindex 0x00*/
extern UNS32 ID7;		/* Mapped at index 0x2006, subindex 0x00*/
extern UNS32 ID8;		/* Mapped at index 0x2007, subindex 0x00*/

#endif // TESTMASTER_H
